/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as LayoutImport } from './routes/_layout'
import { Route as PostRouteImport } from './routes/post/route'
import { Route as SettingsSettingsidImport } from './routes/settings.$settingsid'
import { Route as PostPostidImport } from './routes/post/$postid'
import { Route as LayoutUserRouteImport } from './routes/_layout/user/route'
import { Route as PostPostPostidImport } from './routes/post/post.$postid'
import { Route as LayoutUserUsernameImport } from './routes/_layout/user/$username'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const PostRouteRoute = PostRouteImport.update({
  path: '/post',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SettingsSettingsidRoute = SettingsSettingsidImport.update({
  path: '/$settingsid',
  getParentRoute: () => SettingsRoute,
} as any)

const PostPostidRoute = PostPostidImport.update({
  path: '/$postid',
  getParentRoute: () => PostRouteRoute,
} as any)

const LayoutUserRouteRoute = LayoutUserRouteImport.update({
  path: '/user',
  getParentRoute: () => LayoutRoute,
} as any)

const PostPostPostidRoute = PostPostPostidImport.update({
  path: '/post/$postid',
  getParentRoute: () => PostRouteRoute,
} as any)

const LayoutUserUsernameRoute = LayoutUserUsernameImport.update({
  path: '/$username',
  getParentRoute: () => LayoutUserRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout/user': {
      id: '/_layout/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof LayoutUserRouteImport
      parentRoute: typeof LayoutImport
    }
    '/post/$postid': {
      id: '/post/$postid'
      path: '/$postid'
      fullPath: '/post/$postid'
      preLoaderRoute: typeof PostPostidImport
      parentRoute: typeof PostRouteImport
    }
    '/settings/$settingsid': {
      id: '/settings/$settingsid'
      path: '/$settingsid'
      fullPath: '/settings/$settingsid'
      preLoaderRoute: typeof SettingsSettingsidImport
      parentRoute: typeof SettingsImport
    }
    '/_layout/user/$username': {
      id: '/_layout/user/$username'
      path: '/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof LayoutUserUsernameImport
      parentRoute: typeof LayoutUserRouteImport
    }
    '/post/post/$postid': {
      id: '/post/post/$postid'
      path: '/post/$postid'
      fullPath: '/post/post/$postid'
      preLoaderRoute: typeof PostPostPostidImport
      parentRoute: typeof PostRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  PostRouteRoute: PostRouteRoute.addChildren({
    PostPostidRoute,
    PostPostPostidRoute,
  }),
  LayoutRoute: LayoutRoute.addChildren({
    LayoutUserRouteRoute: LayoutUserRouteRoute.addChildren({
      LayoutUserUsernameRoute,
    }),
  }),
  SettingsRoute: SettingsRoute.addChildren({ SettingsSettingsidRoute }),
  AboutLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/post",
        "/_layout",
        "/settings",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/post": {
      "filePath": "post/route.tsx",
      "children": [
        "/post/$postid",
        "/post/post/$postid"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/user"
      ]
    },
    "/settings": {
      "filePath": "settings.tsx",
      "children": [
        "/settings/$settingsid"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_layout/user": {
      "filePath": "_layout/user/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/user/$username"
      ]
    },
    "/post/$postid": {
      "filePath": "post/$postid.tsx",
      "parent": "/post"
    },
    "/settings/$settingsid": {
      "filePath": "settings.$settingsid.tsx",
      "parent": "/settings"
    },
    "/_layout/user/$username": {
      "filePath": "_layout/user/$username.tsx",
      "parent": "/_layout/user"
    },
    "/post/post/$postid": {
      "filePath": "post/post.$postid.tsx",
      "parent": "/post"
    }
  }
}
ROUTE_MANIFEST_END */
